services:
    database:
        image: mariadb:11
        ports:
            - '3309:3306'
        volumes:
            - ./init:/docker-entrypoint-initdb.d/
        environment:
            MYSQL_ROOT_PASSWORD: password
            MYSQL_DATABASE: file_manager
        healthcheck:
            test: ['CMD', 'healthcheck.sh', '--connect', '--innodb_initialized']
            start_period: 5s
            interval: 5s
            timeout: 5s
            retries: 3

    express:
        image: node:23
        ports:
            - '8090:3000'
        volumes:
            - ./app:/app
        env_file:
            - ./.env
        command: sh -c "cd /app && npm install && npm run dev"
        depends_on:
            database:
                condition: service_healthy
