services:
    database:
        image: mariadb:11
        ports:
            - '3309:3306'
        volumes:
            - ./init:/docker-entrypoint-initdb.d/
            - ./db-data:/var/lib/mysql
        environment:
            MYSQL_ROOT_PASSWORD: password
            MYSQL_DATABASE: file_manager
        healthcheck:
            test: ['CMD', 'healthcheck.sh', '--connect', '--innodb_initialized']
            start_period: 5s
            interval: 5s
            timeout: 5s
            retries: 3

    express:
        ports:
            - '8090:3001'
        volumes:
            - ./app:/app
            - /app/node_modules
        env_file:
            - ./.env.dist
        build:
            context: ./app
            dockerfile: Dockerfile
        depends_on:
            database:
                condition: service_healthy

    react:
        image: node:23
        ports:
            - '3001:3000'
        volumes:
            - ./frontend:/frontend
            - /frontend/node_modules
        build:
            context: ./frontend
            dockerfile: Dockerfile
